[package]
name = "user_lib"
version = "0.1.0"
authors = ["Chenlinfeng <1925466036@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.11.0"
bitflags = "1.3.2"
